### ISSUE TITLE
是否考虑vite

### ISSUE THREAD

**Issue by JinXinAuzn** [youliso/electron-vue3#2]
vite 调试更新极快

**Comment by youliso** [comment]
还在测试兼容性阶段

**Comment by youliso** [comment]
> vite 调试更新极快

vite现在还不完备，会在后续完备后换成vite。
针对调试更新的速度问题现在已切换esbuild-loader进行代码解析 性能有很大的提升(大概80%-90%提升) 你可以试试

**Comment by JinXinAuzn** [comment]
> > vite 调试更新极快
> 
> vite现在还不完备，会在后续完备后换成vite。
> 针对调试更新的速度问题现在已切换esbuild-loader进行代码解析 性能有很大的提升(大概80%-90%提升) 你可以试试

好的👌
