### ISSUE TITLE
关于全局provide 状态管理的问题

### ISSUE THREAD

**Issue by qaw944416252** [youliso/electron-vue3#3]
可以问一下您封装的
export const provideState = (key: string, args: { [key: string]: unknown }) =>
  provide(Symbol(key), reactive(args));
export const getProvideState = (key: string) => inject(Symbol(key));
如何使用吗
我看文档没太明白
跪谢

**Comment by youliso** [comment]
[文档链接](https://v3.cn.vuejs.org/guide/component-provide-inject.html#provide-inject)
