### ISSUE TITLE
如何添加vue-devtools

### ISSUE THREAD

**Issue by lm0xfffe** [youliso/electron-vue3#4]
请问如何添加vue-devtools

**Comment by youliso** [comment]
在[此处](https://github.com/youliso/electron-vue3/blob/master/src/main/index.ts#L76)后面添加就行，参考vue-devtools文档就行

**Comment by lm0xfffe** [comment]
谢谢大佬 ![Uploading image.png…]()

**Comment by lm0xfffe** [comment]
谢谢大佬(๑•̀ㅂ•́)و✧
